
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 35;
  public static final int PAR2 = 20;
  public static final int PAR1 = 19;
  public static final int CONST = 16;
  public static final int CHAR = 17;
  public static final int REMOVE = 61;
  public static final int ENTERO = 3;
  public static final int CAS = 52;
  public static final int XOR = 38;
  public static final int CORCHETEC = 55;
  public static final int DOUBLE = 13;
  public static final int CONTINUE = 51;
  public static final int CORCHETEA = 54;
  public static final int INT = 14;
  public static final int PRINTLN = 11;
  public static final int FOR = 47;
  public static final int MATCH = 44;
  public static final int NOT = 39;
  public static final int AND = 37;
  public static final int FINCADENA = 10;
  public static final int APPEND = 60;
  public static final int SIGNOCASOMATCH = 45;
  public static final int MAYORQUE = 32;
  public static final int IGUAL = 34;
  public static final int CARACTER = 5;
  public static final int OR = 36;
  public static final int BOOL = 18;
  public static final int INCREMENTO = 8;
  public static final int IF = 42;
  public static final int UMENOS = 23;
  public static final int LISTA = 58;
  public static final int ID = 7;
  public static final int EOF = 0;
  public static final int DECIMAL = 4;
  public static final int MAYORIGUALQUE = 33;
  public static final int NEW = 59;
  public static final int DECREMENTO = 9;
  public static final int error = 1;
  public static final int COMA = 53;
  public static final int CADENA = 2;
  public static final int MODULO = 27;
  public static final int NEGACION = 29;
  public static final int MENOS = 22;
  public static final int BREAK = 50;
  public static final int VOID = 56;
  public static final int MENORQUE = 30;
  public static final int POTENCIA = 26;
  public static final int ELSE = 43;
  public static final int PUNTO = 62;
  public static final int SIGNODEFAULTMATCH = 46;
  public static final int START_WITH = 57;
  public static final int WHILE = 48;
  public static final int COMPARACIONIGUALIGUAL = 28;
  public static final int BOOLEANO = 6;
  public static final int MENORIGUALQUE = 31;
  public static final int STRING = 12;
  public static final int DIVISION = 25;
  public static final int LLAVEC = 41;
  public static final int LLAVEA = 40;
  public static final int VAR = 15;
  public static final int DO = 49;
  public static final int MULTIPLICACION = 24;
  public static final int MAS = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "ENTERO",
  "DECIMAL",
  "CARACTER",
  "BOOLEANO",
  "ID",
  "INCREMENTO",
  "DECREMENTO",
  "FINCADENA",
  "PRINTLN",
  "STRING",
  "DOUBLE",
  "INT",
  "VAR",
  "CONST",
  "CHAR",
  "BOOL",
  "PAR1",
  "PAR2",
  "MAS",
  "MENOS",
  "UMENOS",
  "MULTIPLICACION",
  "DIVISION",
  "POTENCIA",
  "MODULO",
  "COMPARACIONIGUALIGUAL",
  "NEGACION",
  "MENORQUE",
  "MENORIGUALQUE",
  "MAYORQUE",
  "MAYORIGUALQUE",
  "IGUAL",
  "DOSPUNTOS",
  "OR",
  "AND",
  "XOR",
  "NOT",
  "LLAVEA",
  "LLAVEC",
  "IF",
  "ELSE",
  "MATCH",
  "SIGNOCASOMATCH",
  "SIGNODEFAULTMATCH",
  "FOR",
  "WHILE",
  "DO",
  "BREAK",
  "CONTINUE",
  "CAS",
  "COMA",
  "CORCHETEA",
  "CORCHETEC",
  "VOID",
  "START_WITH",
  "LISTA",
  "NEW",
  "APPEND",
  "REMOVE",
  "PUNTO"
  };
}

