
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMPARACIONIGUALIGUAL = 18;
  public static final int MENOS = 12;
  public static final int MULTIPLICACION = 14;
  public static final int CADENA = 2;
  public static final int FINCADENA = 7;
  public static final int DECIMAL = 4;
  public static final int DIVISION = 15;
  public static final int NEGACION = 19;
  public static final int POTENCIA = 16;
  public static final int MAYORQUE = 22;
  public static final int MODULO = 17;
  public static final int UMENOS = 13;
  public static final int BOOLEANO = 6;
  public static final int CARACTER = 5;
  public static final int EOF = 0;
  public static final int PRINTLN = 8;
  public static final int MENORIGUALQUE = 21;
  public static final int MENORQUE = 20;
  public static final int error = 1;
  public static final int PAR2 = 10;
  public static final int PAR1 = 9;
  public static final int ENTERO = 3;
  public static final int MAYORIGUALQUE = 23;
  public static final int MAS = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "ENTERO",
  "DECIMAL",
  "CARACTER",
  "BOOLEANO",
  "FINCADENA",
  "PRINTLN",
  "PAR1",
  "PAR2",
  "MAS",
  "MENOS",
  "UMENOS",
  "MULTIPLICACION",
  "DIVISION",
  "POTENCIA",
  "MODULO",
  "COMPARACIONIGUALIGUAL",
  "NEGACION",
  "MENORQUE",
  "MENORIGUALQUE",
  "MAYORQUE",
  "MAYORIGUALQUE"
  };
}

